version: '3'
services:
  archi_steam_farm:
    container_name: archi_steam_farm
    image: justarchi/archisteamfarm:latest
    volumes:
      - ./archi_steam_farm_config:/app/config
    ports:
      - 1242:1242
    environment:
      - TZ=America/Sao_Paulo
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - pi_hole

  pi_hole:
    container_name: pi_hole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8081:80/tcp
    environment:
      - TZ=America/Sao_Paulo
      - VIRTUAL_HOST=pi.hole
      - PROXY_LOCATION=pi.hole
      - ServerIP=192.0.0.1
    volumes:
      - ./pihole_storage/etc-pihole:/etc/pihole
      - ./pihole_storage/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    hostname: pi.hole
    dns:
      - 127.0.0.1
      - 8.8.8.8

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    depends_on:
      - pi_hole

  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    volumes:
      - ./dashy_config/conf.yml:/app/public/conf.yml
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 4000:80
    depends_on:
      - pi_hole
 
  file_browser:
    container_name: file_browser
    image: filebrowser/filebrowser
    restart: unless-stopped
    volumes:
      - /DRIVE/share:/srv
      - ./file_browser_config/database.db:/database.db
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8080:80
    depends_on:
      - pi_hole

        #  homebridge:
        #container_name: homebridge
        #image: oznu/homebridge:latest
        # restart: unless-stopped
        #network_mode: host
        #environment:
        #- PGID=1001
        #- PUID=1001
        #- HOMEBRIDGE_CONFIG_UI=1
        #- HOMEBRIDGE_CONFIG_UI_PORT=8581
        #- TZ=America/Sao_Paulo
        #volumes:
        #- ./homebridge_config:/homebridge
        #depends_on:
        #- pi_hole

        # control_fan:
  #   container_name: control_fan
  #   build: ./control_fan
  #   devices:
  #     - /dev/gpiomem:/dev/gpiomem
  #   network_mode: "host"
